# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conso_eur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('juillet', models.FloatField()),
                ('aout', models.FloatField()),
                ('septembre', models.FloatField()),
                ('octobre', models.FloatField()),
                ('novembre', models.FloatField()),
                ('decembre', models.FloatField()),
                ('janvier', models.FloatField()),
                ('fevrier', models.FloatField()),
                ('mars', models.FloatField()),
                ('avril', models.FloatField()),
                ('mai', models.FloatField()),
                ('juin', models.FloatField()),
                ('yearly_evolution', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conso_watt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('juillet', models.FloatField()),
                ('aout', models.FloatField()),
                ('septembre', models.FloatField()),
                ('octobre', models.FloatField()),
                ('novembre', models.FloatField()),
                ('decembre', models.FloatField()),
                ('janvier', models.FloatField()),
                ('fevrier', models.FloatField()),
                ('mars', models.FloatField()),
                ('avril', models.FloatField()),
                ('mai', models.FloatField()),
                ('juin', models.FloatField()),
                ('yearly_evolution', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('chauffage', models.FloatField()),
                ('cuisson', models.FloatField()),
                ('froid', models.FloatField()),
                ('chauffeeau', models.FloatField()),
                ('electromenager', models.FloatField()),
                ('autres', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
