# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conso_eur',
            name='client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conso_watt',
            name='client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usage',
            name='client',
            field=models.CharField(max_length=200),
        ),
    ]
