# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160522_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usage',
        ),
        migrations.RemoveField(
            model_name='conso_eur',
            name='yearly_evolution',
        ),
        migrations.RemoveField(
            model_name='conso_watt',
            name='yearly_evolution',
        ),
        migrations.AddField(
            model_name='conso_eur',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conso_watt',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conso_eur',
            name='client',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conso_watt',
            name='client',
            field=models.IntegerField(),
        ),
    ]
