# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180411_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conso_eur',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='conso_watt',
            old_name='client',
            new_name='client_id',
        ),
    ]
